# Global section
checksum:
  name_template: '{{ .Tag }}-{{ time "20060102" }}-checksums.txt'

snapshot:
  name_template: '{{ .Env.PACKAGE_NAME_PREFIX }}-{{ time "20060102" }}'

release:
  disable: true

changelog:
  filters:
    exclude:
      # [skip changelog], [skip-changelog], [changelog skip], [changelog-skip]
      - '^(?i)\[(skip|changelog)[ ,-](skip|changelog)\].*'

# We have multiple builds in order to fine tune
# cross compilations.
builds:
  - # OSX
    id: arduino_lint_osx
    binary: arduino-lint
    env:
      - CGO_ENABLED=1
      - CXXFLAGS="-mmacosx-version-min=10.10"
      - CC=/usr/x86_64-apple-darwin14/bin/cc
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/arduino/arduino-lint/configuration.version={{.Tag}}
      - -X github.com/arduino/arduino-lint/configuration.commit={{ .ShortCommit }}
      - -X github.com/arduino/arduino-lint/configuration.buildTimestamp={{.Date}}
  - # ARM
    id: arduino_lint_arm
    binary: arduino-lint
    env:
      - CGO_ENABLED=1
      - CC=/usr/arm-linux-gnueabi/bin/cc
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6
    ldflags:
      - -s -w
      - -X github.com/arduino/arduino-lint/configuration.version={{.Tag}}
      - -X github.com/arduino/arduino-lint/configuration.commit={{ .ShortCommit }}
      - -X github.com/arduino/arduino-lint/configuration.buildTimestamp={{.Date}}
      - "-extldflags '-static'"
  - # ARMv7
    id: arduino_lint_armv7
    binary: arduino-lint
    env:
      - CGO_ENABLED=1
      - CC=/usr/arm-linux-gnueabihf/bin/cc
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
    ldflags:
      - -s -w
      - -X github.com/arduino/arduino-lint/configuration.version={{.Tag}}
      - -X github.com/arduino/arduino-lint/configuration.commit={{ .ShortCommit }}
      - -X github.com/arduino/arduino-lint/configuration.buildTimestamp={{.Date}}
      - "-extldflags '-static'"
  - # ARM64
    id: arduino_lint_arm64
    binary: arduino-lint
    env:
      - CGO_ENABLED=1
      - CC=/usr/aarch64-linux-gnu/bin/cc
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X github.com/arduino/arduino-lint/configuration.version={{.Tag}}
      - -X github.com/arduino/arduino-lint/configuration.commit={{ .ShortCommit }}
      - -X github.com/arduino/arduino-lint/configuration.buildTimestamp={{.Date}}
      - "-extldflags '-static'"
  - # All the other platforms
    id: arduino_lint
    binary: arduino-lint
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - 386
    ldflags:
      - -s -w
      - -X github.com/arduino/arduino-lint/configuration.version={{.Tag}}
      - -X github.com/arduino/arduino-lint/configuration.commit={{ .ShortCommit }}
      - -X github.com/arduino/arduino-lint/configuration.buildTimestamp={{.Date}}
      - "-extldflags '-static'"

archives:
  - id: "arduino_lint"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64bit
      darwin: macOS
      386: 32bit
      arm: ARM
      arm64: ARM64
      linux: Linux
      windows: Windows
    files:
      - LICENSE.txt
