// Code generated by "stringer -type=Type -linecomment"; DO NOT EDIT.

package rulemode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Strict-0]
	_ = x[Specification-1]
	_ = x[Permissive-2]
	_ = x[LibraryManagerSubmission-3]
	_ = x[LibraryManagerIndexed-4]
	_ = x[LibraryManagerIndexing-5]
	_ = x[Official-6]
	_ = x[Default-7]
}

const _Type_name = "strictspecificationpermissivesubmitupdateARDUINO_LINT_LIBRARY_MANAGER_INDEXINGARDUINO_LINT_OFFICIALdefault"

var _Type_index = [...]uint8{0, 6, 19, 29, 35, 41, 78, 99, 106}

func (i Type) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Type_index)-1 {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[idx]:_Type_index[idx+1]]
}
