// Code generated by "stringer -type=Level -linecomment"; DO NOT EDIT.

package checklevel

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Info-0]
	_ = x[Warning-1]
	_ = x[Error-2]
	_ = x[Pass-3]
}

const _Level_name = "infowarningerrorpass"

var _Level_index = [...]uint8{0, 4, 11, 16, 20}

func (i Level) String() string {
	if i < 0 || i >= Level(len(_Level_index)-1) {
		return "Level(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
