---
name: github.com/kevinburke/ssh_config
version: v1.2.0
type: go
summary: Package ssh_config provides tools for manipulating SSH config files.
homepage: https://pkg.go.dev/github.com/kevinburke/ssh_config
license: mit
licenses:
- sources: LICENSE
  text: |
    Copyright (c) 2017 Kevin Burke.

    Permission is hereby granted, free of charge, to any person
    obtaining a copy of this software and associated documentation
    files (the "Software"), to deal in the Software without
    restriction, including without limitation the rights to use,
    copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following
    conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
    OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
    NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
    HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
    WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
    OTHER DEALINGS IN THE SOFTWARE.

    ===================

    The lexer and parser borrow heavily from github.com/pelletier/go-toml. The
    license for that project is copied below.

    The MIT License (MIT)

    Copyright (c) 2013 - 2017 Thomas Pelletier, Eric Anderton

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
notices:
- sources: AUTHORS.txt
  text: |-
    Carlos A Becker <caarlos0@gmail.com>
    Dustin Spicuzza <dustin@virtualroadside.com>
    Eugene Terentev <eugene@terentev.net>
    Kevin Burke <kevin@burke.dev>
    Mark Nevill <nev@improbable.io>
    Scott Lessans <slessans@gmail.com>
    Sergey Lukjanov <me@slukjanov.name>
    Wayne Ashley Berry <wayneashleyberry@gmail.com>
    santosh653 <70637961+santosh653@users.noreply.github.com>
