// This file is part of arduino-lint.
//
// Copyright 2020 ARDUINO SA (http://www.arduino.cc/)
//
// This software is released under the GNU General Public License version 3,
// which covers the main part of arduino-lint.
// The terms of this license can be found at:
// https://www.gnu.org/licenses/gpl-3.0.en.html
//
// You can be released from the requirements of the above licenses by purchasing
// a commercial license. Buying such a license is mandatory if you want to
// modify or otherwise use the software for commercial activities involving the
// Arduino software without disclosing the source code of your own applications.
// To purchase a commercial license, send an email to license@arduino.cc.

package projectdata

import (
	"github.com/arduino/arduino-cli/arduino/cores/packageindex"
)

// InitializeForPackageIndex gathers the package index rule data for the specified project.
func InitializeForPackageIndex() {
	if ProjectPath() != nil {
		packageIndex, packageIndexLoadError = packageindex.LoadIndex(ProjectPath())
	}
}

var packageIndex *packageindex.Index

// PackageIndex returns the packageindex.Index object generated by Arduino CLI.
func PackageIndex() *packageindex.Index {
	return packageIndex
}

var packageIndexLoadError error

// PackageIndexLoadError returns the error return of packageindex.LoadIndex().
func PackageIndexLoadError() error {
	return packageIndexLoadError
}
