// Code generated by "stringer -type=Type -linecomment"; DO NOT EDIT.

package rulelevel

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Info-0]
	_ = x[Warning-1]
	_ = x[Error-2]
	_ = x[Notice-3]
}

const _Type_name = "INFOWARNINGERRORNOTICE"

var _Type_index = [...]uint8{0, 4, 11, 16, 22}

func (i Type) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Type_index)-1 {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[idx]:_Type_index[idx+1]]
}
