// Code generated by "stringer -type=Type -linecomment"; DO NOT EDIT.

package checkmode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Permissive-0]
	_ = x[LibraryManagerSubmission-1]
	_ = x[LibraryManagerIndexed-2]
	_ = x[Official-3]
	_ = x[All-4]
	_ = x[Default-5]
}

const _Type_name = "--permissive--library-manager=submit--library-manager=updateARDUINO_CHECK_OFFICIALalwaysdefault"

var _Type_index = [...]uint8{0, 12, 36, 60, 82, 88, 95}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
