# Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-workflows-task.md
name: Check Workflows

# See: https://docs.github.com/actions/reference/workflows-and-actions/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/*.ya?ml"
      - ".npmrc"
      - "package.json"
      - "package-lock.json"
      - "Taskfile.ya?ml"
  pull_request:
    paths:
      - ".github/workflows/*.ya?ml"
      - ".npmrc"
      - "package.json"
      - "package-lock.json"
      - "Taskfile.ya?ml"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage resulting from changes to the JSON schema.
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: package.json

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Validate workflows
        run: |
          task \
            --silent \
            ci:validate
